### ISSUE TITLE
Padding issue are here, give some user feedback on submit button click.

### ISSUE THREAD

**Issue by nitansh11** [sandeshjadhav5/Bath-Body-Works-E-commerce-Website-Clone#55]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/8274883/212795047-f3764379-3679-44ad-84a6-09b0ea2b36eb.png">

**Comment by sandeshjadhav5** [comment]
- provided padding between button and input box
- feedback provided after clicking on button
