### ISSUE TITLE
Responsive issue in signup page, horizontal scroll is coming

### ISSUE THREAD

**Issue by nitansh11** [sandeshjadhav5/Bath-Body-Works-E-commerce-Website-Clone#57]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/8274883/212795450-e902ba9f-77bb-4f7d-975c-96be0842ca01.png">

**Comment by sandeshjadhav5** [comment]
- added responsiveness to the signup page
-will work for all screen sizes now
