### ISSUE TITLE
Not able to type my first name  on sign up page on deployed website. Also alignment(left space) for Label : First name etc. is not correct

### ISSUE THREAD

**Issue by nitansh11** [sandeshjadhav5/Bath-Body-Works-E-commerce-Website-Clone#58]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/8274883/212795617-22106c06-9de4-4b2f-8042-983963a7faf8.png">

**Comment by sandeshjadhav5** [comment]
- bug fixed
- now able to enter input details in all input fields
