### ISSUE TITLE
Bug: if we reload on sign up page, we are getting page not found

### ISSUE THREAD

**Issue by nitansh11** [sandeshjadhav5/Bath-Body-Works-E-commerce-Website-Clone#59]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/8274883/212795809-aaf43b77-c894-4084-ad02-c6446ff4f04d.png">

**Comment by nitansh11** [comment]
route name for sign up page should be appropriate, it should not be loginpage2

**Comment by sandeshjadhav5** [comment]
- fixed this issue
- renamed route name from login2 to signup
