### ISSUE TITLE
When hover on + icon, its getting merged with add to card button. Add some space here

### ISSUE THREAD

**Issue by nitansh11** [sandeshjadhav5/Bath-Body-Works-E-commerce-Website-Clone#62]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/8274883/212796454-580920e9-f0a1-4202-a28b-23ace88ff348.png">

**Comment by sandeshjadhav5** [comment]
- fixed this issue
- provided margin between add to bag button and increase quantity button
- onhover color is also changed
