### ISSUE TITLE
Important: Basic purchase flow is not working on deployed link, was working in video presentation

### ISSUE THREAD

**Issue by nitansh11** [sandeshjadhav5/Bath-Body-Works-E-commerce-Website-Clone#69]
Make sure this flow works in deployed website:

User signup-> user sign in -> user go to products page -> user add product to cart -> user apply coupon -> user checkout after adding address -> user does payment.

**Comment by sandeshjadhav5** [comment]
- fixed this issue 
- basic purchase flow is now working properly
- provided private route
