### ISSUE TITLE
Authentication/signin api calls  is missing on admin side. Able to enter any email and password and getting logged in.

### ISSUE THREAD

**Issue by nitansh11** [sandeshjadhav5/Bath-Body-Works-E-commerce-Website-Clone#71]

**Comment by nitansh11** [comment]
Email password validation should be there on input fields

**Comment by sandeshjadhav5** [comment]
resolved this issue , now using reqres API for login as admin

- admin will be able to login only when he enters "eve.holt@reqres.in" as email
